### ISSUE TITLE
Piechart portions visually incorrect when under certain conditions

### ISSUE THREAD

**Issue by Phat-pham99** [va-h/term-piechart#1]
When data input to piechart not divisible to 100 (or certain data inputs), Piechart portions visually seems incorrect. For instance, in this example, while E < C, it seems larger on the chart.
```
from term_piechart import Pie

data=[
    {"name": "A", "value": 80},
    {"name": "C", "value": 60},
    {"name": "E", "value": 50},
    {"name": "B", "value": 20},
    {"name": "D", "value": 13}
]
print((Pie(data, radius=10, autocolor=True, fill="o")))
```
![term_piechart_BUG](https://github.com/va-h/term-piechart/assets/57822898/1494fe19-f8d6-4482-99eb-1d11923bf932)

When data input is divisible to 100 , things works like normal
```
data=[
    {"name": "A", "value": 50},
    {"name": "B", "value": 25},
    {"name": "C", "value": 10},
    {"name": "D", "value": 9},
    {"name": "E", "value": 6}
]

print((Pie(data, radius=10, autocolor=True, fill="o")))
```
![term_piechart_PASSED](https://github.com/va-h/term-piechart/assets/57822898/0e93079d-6a61-44df-8e7f-16abf88638fe)

**Comment by va-h** [comment]
Hello you are right,
this is a result of the aspect_ratio variable defaulting to 2 to make the circle appear round in a common terminal where a character height is mostly twice the character width. The angles are calculated correctly but the horizontal stretch leads to this looking wrong. Which unfortunately means the base 100 only appears visually correct but isn't really.

You can get a "visually" correct circle by passing aspect_ratio 1 to the instance of Pie.

```python
from term_piechart import Pie

data=[
    {"name": "A", "value": 80},
    {"name": "C", "value": 60},
    {"name": "E", "value": 50},
    {"name": "B", "value": 20},
    {"name": "D", "value": 13}
]
print((Pie(data, radius=10, autocolor=True, fill="o", aspect_ratio=1)))
```

![grafik](https://github.com/va-h/term-piechart/assets/10695455/4e37b438-85cc-4644-8bed-ce1256737b9a)

**Comment by Phat-pham99** [comment]
@va-h Thank you for the in-depth explanation ! This works perfectly.
